src/objects/Article_Quality__c.object
<CustomObject>
    <description>Following the KCS methodology, each record captures article quality review results that can be summarized to measure overall Knowledge quality.</description>
    <fields>
        <fullName>AQ_Score__c</fullName>
        <label>AQI Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Action_Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coaching Provided By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Articles_Quality3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Date Coaching Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Coaching Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Action_Taken__c</fullName>
        <label>Action Taken</label>
        <picklist>
            <picklistValues>
                <fullName>Article Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Article Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Action Needed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Article Contributor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Articles_Quality</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Art_Meets_Content_Standard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Article meets content standard?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ArticleFirstPublishedDate__c</fullName>
        <description>Article First Published Date</description>
        <label>Article First Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Article_Created_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Article Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Article_Quality_Index</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Article_Created_Date__c</fullName>
        <label>Article Version Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Article_Link__c</fullName>
        <label>Article Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Title__c</fullName>
        <label>Article Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Type__c</fullName>
        <label>Article Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Unique__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Article Unique?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Article_Version__c</fullName>
        <label>Article Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Content_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Content complete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Content_Understandable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Content understandable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Notes__c</fullName>
        <label>Coaching Notes</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Knowledge_Article_Id__c</fullName>
        <label>Knowledge Article</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Knowledge_Article_Version_Id__c</fullName>
        <label>Knowledge Article Version</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Modified_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Article Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Articles_Quality2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Modified_Date__c</fullName>
        <label>Article Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Published_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Article Last Published By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Articles_Quality1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Published_Date__c</fullName>
        <label>Article Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Links_In_Article_Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Links in article valid?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Possible_Points__c</fullName>
        <label>Possible Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Properties_Set_Appropriately__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Properties set appropriately?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Accurate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title Accurate?</label>
        <type>Checkbox</type>
    </fields>
    <label>Article Quality Index</label>
    <nameField>
        <label>Article Quality Index Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Article Quality Index</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ArticleQuality_index__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Art_Meets_Content_Standard__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Article Meets Content Standard</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Article_Unique__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Article unique</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Content_complete__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Content complete</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Content_understandable__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Content understandable</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Links_in_article_valid__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Links in article valid</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Possible_Points__c</fullName>
        <defaultValue>7</defaultValue>
        <label>Possible points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Properties_set_appropriately__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Properties set appropriately</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title_Accurate__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Title accurate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Article Quality Index Definition</label>
</CustomObject>

src/classes/aqi_Ctrl.cls
/**
 * @author Altimetrik
 * @description
 *	started on MM/DD/YYYY
 *	REPLACE_BY_CLASS_LOGIC_RESPONSABILITIES
 **/
public with sharing class aqi_Ctrl {
	// Constants

	//************************************************************************
	// Properties & data members



	//************************************************************************
	// Methods

	public aqi_Ctrl() {
		
	}

	/*
	* @description
	*	returns AQI index api names and values from custom setting
	* @params
	*	none
	* @return 
	*	Map<String,Double> : api_name, decimal value ( index weight)
	*/
	public static Map<String,Double>  getindexApiNameToValue(){
        ArticleQuality_index__c aqs = ArticleQuality_index__c.getInstance('default');
        Map<String, Schema.SObjectField> allFields = Schema.SObjectType.ArticleQuality_index__c.fields.getMap();

        Map<String,Double> result = new Map<String,Double>();  
        Double idx_val;   
        String idx_api_name;
		if (aqs != null){
			for(String str : allFields.keySet()){  
				Schema.DescribeFieldResult dfr = allFields.get(str).getDescribe();
				idx_api_name = dfr.getName();         	
				if (dfr.getType() ==Schema.DisplayType.DOUBLE ){

					//system.debug('\n'+str+':'+idx_api_name+' - '+dfr.getType());
					system.debug(aqs);
					Object obj = aqs.get(idx_api_name);
					idx_val =  Double.valueOf(obj);   
					//system.debug('\n'+str+':'+idx_api_name+' - '+dfr.getType()+' value '+idx_val);
					result.put(idx_api_name,idx_val);
				}
			}
		}
    

        return result;
    }

	/*
	* @description
	*	returns AQI record if it find a match
	* @params
	*	Id kaId Id if kav article related to current AQI record
	*	String kaLang kav language
	*   String kaVersion version number
	* @return 
	*	Article_Quality__c aqi record
	*/
	public static Article_Quality__c findDupe(Id kaId, String kaLang, String kaVersion){

		try{
 
			aqi_SecurityHandler.canAccess(Article_Quality__c.sObjectType);

			list<Article_Quality__c > kavList = [SELECT
													Action_Assigned_To__c,Action_Date__c,Action_Needed__c,Action_Taken__c,
													AQ_Score__c,Article_Link__c,Article_Number__c,Article_Title__c,
													Article_Created_By__c ,Article_Created_Date__c,
													Article_Type__c,Article_Unique__c,Article_Version__c,
													Art_Meets_Content_Standard__c,Comment__c,Content_Complete__c,
													Content_Understandable__c,Internal_Notes__c,ArticleFirstPublishedDate__c,
													Language__c,Last_Modified_By__c,Last_Modified_Date__c,Last_Published_By__c,
													Last_Published_Date__c,Links_In_Article_Valid__c,Possible_Points__c,
													Properties_Set_Appropriately__c,Title_Accurate__c,Agent__c,Knowledge_Article_Version_Id__c,
													Knowledge_Article_Id__c
											FROM Article_Quality__c
											WHERE
												Knowledge_Article_Id__c =: kaId AND
												Article_Version__c =: Decimal.valueOf(kaVersion) AND
												Language__c =: kaLang
												limit 1];

                if (!kavList.isEmpty())
                    return kavList.get(0);
                else
                    return null;

            }catch(Exception e){
                 ApexPages.addMessage(new ApexPages.Message(
                    ApexPages.Severity.ERROR,
                    e.getMessage()
                ));
            }
            return null;
        }

}