src/objects/Article_Quality__c.object
<CustomObject>
    <description>Following the KCS methodology, each record captures article quality review results that can be summarized to measure overall Knowledge quality.</description>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Article Contributor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Articles_Quality</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Art_Meets_Content_Standard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Article meets content standard?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Article_Link__c</fullName>
        <label>Article Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Title__c</fullName>
        <label>Article Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Unique__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Article Unique?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Article_Version__c</fullName>
        <label>Article Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Content_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Content complete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Content_Understandable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Content understandable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Knowledge_Article_Id__c</fullName>
        <label>Knowledge Article</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Knowledge_Article_Version_Id__c</fullName>
        <label>Knowledge Article Version</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Modified_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Article Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Articles_Quality2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Modified_Date__c</fullName>
        <label>Article Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Published_Date__c</fullName>
        <label>Article Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Links_In_Article_Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Links in article valid?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Possible_Points__c</fullName>
        <label>Possible Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Properties_Set_Appropriately__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Properties set appropriately?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Accurate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title Accurate?</label>
        <type>Checkbox</type>
    </fields>
    <label>Article Quality Index</label>
    <nameField>
        <label>Article Quality Index Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Article Quality Index</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ArticleQuality_index__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Art_Meets_Content_Standard__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Article Meets Content Standard</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Article_Unique__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Article unique</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Content_complete__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Content complete</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Content_understandable__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Content understandable</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Links_in_article_valid__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Links in article valid</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Possible_Points__c</fullName>
        <defaultValue>7</defaultValue>
        <label>Possible points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Properties_set_appropriately__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Properties set appropriately</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selected_Languages__c</fullName>
        <defaultValue>&quot;en_US&quot;</defaultValue>
        <description>Comma separated list of Knowledge articles languages for the search page</description>
        <label>Selected languages</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Accurate__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Title accurate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Article Quality Index Definition</label>
</CustomObject>

src/classes/aqi_KnowledgeSearchCtrlV2_Test.cls
@isTest
private class aqi_KnowledgeSearchCtrlV2_Test {
    static SObject kavObj;
    static void populateCustomSetting(){
        //creates a Custom Setting at the organization level
        ArticleQuality_index__c setting= new ArticleQuality_index__c();
        setting.Name = 'default';
        setting.Art_Meets_Content_Standard__c = 2;
        setting.Article_Unique__c = 2;
        setting.Content_complete__c = 2;
        setting.Content_understandable__c = 2;
        setting.Links_in_article_valid__c = 2;
        setting.Possible_Points__c = 2;
        setting.Properties_set_appropriately__c = 2;
        setting.Title_Accurate__c = 4;
        setting.Selected_Languages__c = 'en_US';
        insert setting;
    }

    static void populateData(){
        // creates Custom Article type
        string publishStatus = 'Draft';
        Map<String,Schema.SOBjectType> gd = Schema.getGlobalDescribe();
        List<String> kavNames = new List<String>();
        for (String s : gd.keySet()) {
            if (s.contains('__kav')) {
                kavNames.add(s);
            }
        }
        String default_language = aqi_SettingsHandler.customOrDefaultLanguage();
        String objType = kavNames.get(0);
        kavObj = Schema.getGlobalDescribe().get(objType).newSObject();
        kavObj.put('Title','test');
        kavObj.put('UrlName', 'foo-foo-foo-test'+String.valueOf(Crypto.getRandomInteger()));
        kavObj.put('Summary', 'This is a summary test!!! Foo. Foo. Foo.');
        kavObj.put('Language', default_language);
        insert kavObj;
        String q =  '    SELECT Id,ArticleNumber,CreatedDate,LastPublishedDate, LastModifiedDate, LastModifiedById,'+
                    '    PublishStatus,Summary,Title,UrlName,VersionNumber,Language ,KnowledgeArticleId '+
                    '   from KnowledgeArticleVersion where Id = \'' +kavObj.get('Id')+  '\' and PublishStatus = :publishStatus';
        kavObj = (KnowledgeArticleVersion)Database.query(q);
    }

    static Article_Quality__c populateFields (KnowledgeArticleVersion article){
           Article_Quality__c result = new Article_Quality__c();
           result.Knowledge_Article_Version_Id__c = article.Id;
           result.Article_Title__c = article.Title;
           result.Knowledge_Article_Id__c = article.KnowledgeArticleId;
           result.Article_Number__c = article.ArticleNumber;
           result.Article_Version__c = article.VersionNumber;
           result.Language__c = article.Language;
           result.Last_Modified_Date__c = article.LastModifiedDate;
           result.Last_Published_Date__c = article.LastPublishedDate;
           result.Last_Modified_By__c = article.LastModifiedById;
           result.Properties_Set_Appropriately__c = false;
           result.Article_Link__c = 'https://login.salesforce.com/' + article.Id;
           result.Article_Unique__c = true;
           result.Art_Meets_Content_Standard__c = true;
           result.Content_Complete__c = true;
           result.Agent__c = UserInfo.getUserId();
           return result;
    }

    @isTest static void test_list() {
        populateCustomSetting();
        System.Test.startTest();
        PageReference tpageRef = Page.aqi_KnowledgeSearch;
        Test.setCurrentPage(tpageRef);
        ApexPages.currentPage().getParameters().put('kavId', UserInfo.getUserId());
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
        System.assertEquals(0, pageMessages.size());
        aqi_KnowledgeSearchCtrlV2 ctr = new aqi_KnowledgeSearchCtrlV2();
        populateData();
        KnowledgeArticleVersion article = (KnowledgeArticleVersion)kavObj;

        String queryString = ctr.resolveArticleSearch();
        System.assertNotEquals(true, String.isBlank(queryString));
        ctr.subject = 'test';
        String queryStringWithSubject = ctr.resolveArticleSearch();
        System.assertNotEquals(true, String.isBlank(queryStringWithSubject)); 
        String queryDefaultArticles = ctr.queryDefaultArticles();
        System.assertNotEquals(true, String.isBlank(queryDefaultArticles));
        String aLanguage = ctr.aLanguage;
        System.assertNotEquals(true, String.isBlank(aLanguage));
        Map<String,String> allLanguageOptions = aqi_KnowledgeSearchCtrlV2.allLanguageOptions;
        System.assertNotEquals(null, allLanguageOptions);
        System.assertNotEquals(false, aqi_KnowledgeSearchCtrlV2.appConfigured);
        String queryPopularArticles = ctr.queryPopularArticles();
        System.assertNotEquals(true, String.isBlank(queryPopularArticles));
        System.assertNotEquals(null, ctr.getMyArticles());
        System.assertNotEquals(null, ctr.getLanguageOptions());
        System.assertEquals(2,(ctr.escapeReservedChars('fa\\')).length());
        List<SelectOption> listRecTypes = ctr.getTheRecordTypes();

        System.Test.stopTest();
     }
}